<?php
require_once "Pigeon.php";
class PigeonOrderLifecycle extends OrderLifecycle
{
    protected function deliveryService(): DeliveryService
    {
        return new Pigeon(); // TODO: Change the autogenerated stub
    }
}